rules_apple: set max_compatibility_level = 3 on rules_swift
This matches [upstream] and hopefully fixes:

```
…/envoy_build_config% bazel build //:extension_registry
ERROR: Error computing the main repository mapping: rules_apple@4.3.3.bcr.1 depends on rules_swift@2.4.0 with compatibility level 2, but
envoy_build@_ depends on rules_swift@3.1.2 with compatibility level 3 which is different
Computing main repo mapping:
…/envoy_build_config%
```

[upstream]: https://github.com/bazelbuild/rules_apple/blob/c26e9b758d756a3470a495907952c27f421480f8/MODULE.bazel#L18