rules_apple: bump rules_swift to 3.1.2 to match what Envoy uses
Still trying to fix:

```
…/envoy_build_config% bazel build //:extension_registry
ERROR: Error computing the main repository mapping: rules_apple@4.3.3.bcr.1 depends on rules_swift@2.4.0 with compatibility level 2, but
envoy_build@_ depends on rules_swift@3.1.2 with compatibility level 3 which is different
Computing main repo mapping:
…/envoy_build_config%
```